"""Get Application properties that have been generated by `create-configs`."""
import json
import logging

LOG = logging.getLogger(__name__)


def get_properties(properties_file='raw.properties.json', env=None):
    """Get contents of _properties_file_ for the _env_.

    Args:
        properties_file (str): File name of `create-configs` JSON output.

    Returns:
        dict: JSON loaded Application properties for _env_.
        None: Given _env_ was not found in `create-configs` JSON output.
    """
    with open(properties_file, 'rt') as file_handle:
        properties = json.load(file_handle)

    env_properties = properties.get(env, properties)
    LOG.debug('Found properties for %s:\n%s', env, env_properties)
    return env_properties
