---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spin-clouddriver-bootstrap-v000
  namespace: spinnaker
spec:
  replicas: 0

---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spin-orca-bootstrap-v000
  namespace: spinnaker
spec:
  replicas: 0

---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spin-redis-bootstrap-v000
  namespace: spinnaker
spec:
  replicas: 0
