``image`` Block
~~~~~~~~~~~~~~~

Holds settings for the baked image

``root_volume_size``
********************

Defines the root volume size of the resulting AMI in GB

    | *Type*: int
    | *Units*: Gigabyte
    | *Default*: `6`
