``services`` Block
~~~~~~~~~~~~~~~~~~

Access to different Cloud Services will be added to an inline Policy for an IAM
Role. Keys must match with a corresponding template in
:file:`src/foremast/templates/infrastructure/iam/{key}.json.j2`.

``cloudformation``
******************

Add CloudFormation access.

   | *Type*: boolean
   | *Default*: ``false``

``cloudwatchlogs``
******************

Add CloudWatch Logs access. Lambda Functions will automatically have this added.

   | *Type*: boolean
   | *Default*: ``false``

``cloudwatch``
**************

Add CloudWatch Limited access.

   | *Type*: boolean
   | *Default*: ``false``

``dynamodb``
************

Add DynamoDB access to tables listed.

   | *Type*: array
   | *Default*: ``[]``

``elasticsearch``
*****************

Add ElasticSearch access to domains listed.

   | *Type*: array
   | *Default*: ``[]``

``firehose``
************

Add Firehose access to streams listed.

   | *Type*: array
   | *Default*: ``[]``

``kinesis``
***********

Add Kinesis Streams access to streams listed.

   | *Type*: array
   | *Default*: ``[]``

``lambda``
**********

Add Lambda access.

   | *Type*: boolean
   | *Default*: ``false``

``rds-db``
**********

Add RDS-DB Connect access to RDS DB Name/RDS DB User key pairs listed.
(http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html)

   | *Type*: object
   | *Default*: ``{}``
   | *Example*: ``{"dbi_resource_id": "db_user", "*": "example_user"}```

``s3``
******

Add S3 access to the provided Bucket. You may need to override default
templates, see :ref:`templates_path`. To access other S3 Buckets, provide a list
of names to add.

   | *Type*: boolean XOR array
   | *Default*: ``false``
   | *Example boolean*:

     .. code-block:: json

        {
          "s3": true
        }

   | *Example array*:

      .. code-block:: json

        {
          "s3": ["other_bucket"]
        }

``sdb``
*******

Add SimpleDB access to SimpleDB Domains listed.

   | *Type*: array
   | *Default*: ``[]``

``ses``
*******

Add SES access.

   | *Type*: boolean
   | *Default*: ``false``

``sns``
*******

Add SNS access.

   | *Type*: boolean
   | *Default*: ``false``

``sqs``
*******

Add SQS access.

   | *Type*: boolean
   | *Default*: ``false``
