``services`` Block
~~~~~~~~~~~~~~~~~~

Access to different Cloud Services will be added to an inline Policy for an IAM
Role. Keys must match with a corresponding template in
:file:`src/foremast/templates/infrastructure/iam/{key}.json.j2`.

``cloudformation``
******************

Add CloudFormation access.

   | *Type*: bool
   | *Default*: ``false``

``cloudwatchlogs``
******************

Add CloudWatch Logs access. Lambda Functions will automatically have this added.

   | *Type*: bool
   | *Default*: ``false``

``dynamodb``
************

Add DynamoDB access to tables listed.

   | *Type*: list
   | *Default*: ``[]``

``elasticsearch``
*****************

Add ElasticSearch access to domains listed.

   | *Type*: list
   | *Default*: ``[]``

``firehose``
************

Add Firehose access to streams listed.

   | *Type*: list
   | *Default*: ``[]``

``kinesis``
************

Add Kinesis Streams access to streams listed.

   | *Type*: list
   | *Default*: ``[]``

``lambda``
**********

Add Lambda access.

   | *Type*: bool
   | *Default*: ``false``

``rds-db``
************

Add RDS-DB Connect access to RDS DB Name/RDS DB User key pairs listed.
(http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html)

   | *Type*: dict
   | *Default*: ``{}``
   | *Example*: ``{"dbi_resource_id": "db_user", "*": "example_user"}```

``s3``
******

Add S3 access. You may need to override default templates, see :ref:`templates_path`. Alternatively, you can provide a list of s3 bucket names to be added to the instance profile.

   | *Type*: bool -or- list
   | *Default*: ``false``

``sdb``
************

Add SimpleDB access to SimpleDB Domains listed.

   | *Type*: list
   | *Default*: ``[]``

``ses``
*******

Add SES access.

   | *Type*: bool
   | *Default*: ``false``

``sns``
*******

Add SNS access.

   | *Type*: bool
   | *Default*: ``false``

``sqs``
*******

Add SQS access.

   | *Type*: bool
   | *Default*: ``false``
